mirai-mamori/Sakurairo

style.css
=> 1.12.5.1（はなふぶき　Update 2）

style.css
=> 1.12.7（はなふぶき　Update 2）

README.md, header.php, inc/classes/Bilibili.php, inc/decorate.php, style.css
改进/提升：
- 夜间模式
修复：
- 移动端开启文字Logo可能会出现白条的问题
=> 1.12.8（はなふぶき　Update 2）

functions.php, style.css, user/page-login.php
改进/提升：
- 默认静态资源更新
修复：
- 登录页面模板致命问题
=> Login Page Fix ＆ Res Update

README.md, footer.php, inc/decorate.php, opt/options/theme-options.php, style.css
增强：
- 控件圆角相关设置
修正：
- 导航菜单圆角设置无法使用的问题
- Readme文件中的标注错误
优化：
- 移动端现在不再显示灯笼
=> 花火「はなび」　Special　Update　Enhancement　Pack

functions.php, user/page-photo.php
=> add Template photo

opt/options/theme-options.php, style.css, tpl/content-thumb.php, tpl/meta-author.php
存在的问题：
目前post-meta部分使用单行span实现，若内容过长会显示不完整
=> feat:首页文章区域:作者信息

tpl/content-thumb.php
原始报错：Warning: Trying to access array offset on value of type bool in /wp-
content/themes/Sakurairo-master/tpl/content-thumb.php on line 19
解决方案：向更小的尺寸回滚
=> fix:修复文章没有'large'尺寸的缩略图时报错的情况

inc/decorate.php, style.css
=> feat:添加全局css变量--theme-skin

user/page-photo.php
用户上传图片错误或未上传图片时 相册模板 页面显示异常 
- [异常页处理](https://www.siroi.top/photo-%E6%97%A0%E5%9B%BE%E7%89%87/)
- [正常页处理](https://www.siroi.top/photo/)
=> add template photo page when user dont upload imgs

css/theme/github.css, css/theme/sakura.css
=> fix:highlight.js代码显示不完整

footer.php, opt/options/theme-options.php
=> feat: 增加选项 为页尾追加HTML代码

opt/options/theme-options.php
=> Translation Correction 1

languages/ja_JP.po
72ではない不够正式改ではありません
145修改emoji位置
246修改翻译，“リクエスト”常用于IT领域
257修改ファイルあたり最大为1ファイルの最大サイズは
修改468数分前为分前
修改647为使用不可文字が含んでいます、有効なユーザー名を入力してください。
完善了703、707、720和724行
修改了743行
修改了751行
修改了743，744行
修改了751，752行
=> Update Japanese translation

functions.php, style.css
A new system UI with Material You that's expressive, dynamic, and personal. Extend your apps with redesigned widgets, AppSearch, Game Mode, and new codecs. Support new protections like privacy dashboard and approximate location. Improve productivity with rich content insertion, easier blurs, improved native debugging, and much more.
=> Fuukei Sakurairo 12

functions.php
不允许为空时可能会出现
Warning: Undefined variable
Warning: Trying to access array offset on value of type null
=> Fix avatar bug

.gitignore, archive.php, author.php, index.php, search.php, tpl/content-thumb.php
=> 同一设置样式与格式化代码

tpl/content-category.php, tpl/content-image.php, tpl/content-single.php, tpl/content-status.php, tpl/content-thumb.php, tpl/content.php, tpl/single-image.php
根据issue #559 将GMT时间戳改为用户的自定义时区设置
=> fix: Change post timezone by user setting

.github/workflows/issue-assignees.temp.yml, .github/workflows/issue-help-wanted.temp.yml, .github/workflows/issue-stale-close.temp.yml
=> chore: add workflows

inc/classes/Bilibili.php
=> fix(追番模板): Division by zero

header.php
将内边距设置为10px，以增大图标容器的点击区域。
`<div class="iconflat no-select" style="padding: 30px;">`
=> 解决主题移动端菜单难以点中的问题

inc/theme_plus.php, layouts/post-nextprev.php
=> 修复：已经设置隐藏的分类里的文章错误显示在了“上/下一篇文章”中

functions.php
=> 修复：自定义统计数据显示格式未生效

functions.php, inc/classes/Captcha.php, inc/decorate.php, inc/swicher.php, opt/options/theme-options.php, style.css
另外修复了一个小问题：[daefe4f383cfde337fdeb85d16f686ae8bc295c5](https://github.com/mirai-mamori/Sakurairo/commit/daefe4f383cfde337fdeb85d16f686ae8bc295c5)
=> 新功能：自定义行内代码背景颜色、自定义Gravatar代理地址

opt/options/theme-options.php
=> 优化后台设置面板用户体验

footer.php, functions.php, layouts/post-nextprev.php, opt/options/theme-options.php, page-word.php, style.css
=> 新功能：友链排序支持；修复：说说模板a标签异常；修复：代码块背景冲突

css/theme/sakura.css, inc/swicher.php, opt/options/theme-options.php, page-word.php, style.css
=> 文章说说样式修正，和错误修复

functions.php
=> fix: 博客找回密码界面验证码无效

comments.php, functions.php, opt/options/theme-options.php, style.css
详细信息：https://kanochan.net/archives/3449.html
=> feat(评论区表情): 新增自定义表情添加功能

README.md, author.php
=> 更改简介文本获取方法,修复了个人简介换行不显示的情况.

functions.php, inc/classes/IpLocation.php, opt/options/theme-options.php
=> 将评论的IP地理位置信息作为元数据存储

404.php, style.css
fix: https://github.com/mirai-mamori/Sakurairo/issues/882
效果：
=> fix(404page): 修正按钮布局

functions.php, header.php
见 #881 , 排除页面和类别的搜索显示结果。顺便也加入一下IE浏览器不兼容问题提示的英文翻译。
=> 搜索结果显示(#881)  和增加IE提示的英文翻译

style.css
[修复评论区无法上传图片](https://github.com/mirai-mamori/Sakurairo/issues/858)
虽然改了下上传按钮的位置就可以用了，但感觉还是玄学问题，因为在之前版本确实是正常的，现在f12一看发现上传按钮被挡住了所以按了才没反应。
k宝说不能复现，我也不清楚😂，我这edge 124.0.2478.51稳定复现🤣。
=> 修复评论区无法上传图片

style.css
=> 修复 查看评论 按钮的阴影显示不全

style.css
Reverts mirai-mamori/Sakurairo#841
=> Revert "修复 查看评论 按钮的阴影显示不全"

opt/classes/setup.class.php
=> Fix theme path on bitnami

404.php, style.css
更改文章导航菜单位置，使之对齐文章首段首行
修改前样式
修改后样式
=> Update toc-container and 404 page

inc/classes/Images.php
=> fix issue #954

header.php
Reverts mirai-mamori/Sakurairo#986
Works on my machine
找找是不是别的问题
少用`new Function`
=> Revert "更换保活脚本的方式，发现直接插入页面不加载了"

tpl/content-thumb.php
=> 每页显示文章数量改为由 WordPress 设置决定

tpl/content-thumb.php
之前直接复制粘贴的搜索页的方法，应该是忘记改变量了
或者是分支搞错了，总之现在没问题了
=> 修复说说首页开关的问题

inc/classes/Bilibili.php, inc/classes/MyAnimeList.php, inc/classes/bangumi.php, opt/options/theme-options.php, tpl/content-thumbcard.php
为追番页添加缓存功能
在用户服务器网络不通透时可以自行获取内容并填充
或服务器自行获取后更新缓存内容，降低后续延迟和负担
修正了一处报错问题
=> 追番页添加了缓存功能

layouts/feature.php
为展示区域添加数据类型检查，添加默认值
防止在部分高版本环境中更新主题后导致崩溃、中断输出或报错的问题
=> 修复可能导致报错的问题

functions.php
=> fix: display abnormally in timeline

inc/classes/gallery.php
更新内建随机图API支持
支持遍历子目录，以方便用户使用可以使用文件夹管理图片，方便整理、更新内容
=> 更新内建随机图API支持子目录

functions.php
=> Support bilibili video embedding.

inc/decorate.php, index.php
修复了ajax加载文章后分页提示穿插在文章中的问题
将分页逻辑移至文章容器外面即可
=> 修复容器和分页层级导致的部分排版问题

layouts/imgbox.php
=> 更改首页top-social的v2下的社交网络滑动切换为可循环

functions.php
Update ghcard shortcode link to open in new tab for external link
=> Update ghcard shortcode link to open in new tab

layouts/sakura_header.php, opt/options/theme-options.php
=> Sakurairo样式支持自定义圆角

comments.php, css/responsive.css, css/sakura_header.css, page-links.php, single.php, style.css, tpl/content-page.php
https://github.com/Fuukei/Sakurairo_Scripts/pull/26
=> script迁移，一处样式错误纠正，基础目录定位

js/nav.js
从主页进入文章页后刷新，导航栏文章标题显示异常，但直接访问文章页正常。
- 异常为导航栏保留主页状态数据，未正确触发文章标题的滚动交换逻辑；正常为初始状态正确识别为非主页，直接应用文章标题逻辑。
- 从主页跳转时`sessionStorage`保存了`lastPageWasHome: true`，刷新后`StateManager`错误认为"上次页面是主页"。
- `initArticleTitleBehavior`在`DOM`加载完成后立即执行，此时滚动位置尚未恢复，导致`getBoundingClientRect()`检测错误。
- 浏览器自动滚动恢复发生在`DOMContentLoaded`之后，现有代码在`DOMContentLoaded`时初始化，早于滚动位置恢复。
- 状态管理修正
- 滚动位置延迟检测
- 增加滚动恢复监听
- 宽度计算容错
- 先清除错误状态，后执行初始化，最后补发滚动检测。
- `300ms`等待滚动恢复，`100ms`重检容错窗口。
- 兼容`Firefox/Chrome`的滚动恢复差异，处理`Safari`的滚动恢复延迟问题。
- 保留原有`handleScroll`逻辑，新增代码作为补充而非替换。
- 确保在刷新页面时，正确识别当前实际页面状态，等待浏览器完成滚动位置恢复执行二次宽度检测和修正，强制触发文章标题交换逻辑。
=> 修复了新版导航栏的一些问题

functions.php, inc/theme-plus.php
修复部分情况下找不到WP_Filesystem()方法的问题
删除已废弃的函数
修复了后台侧边导航栏飞出去的问题
前
https://github.com/user-attachments/assets/3632a91d-3262-42ad-83c8-bf8c9fa5fa27
后
https://github.com/user-attachments/assets/a2df0c07-df6a-499d-81e2-90c4e9b3b60a
=> 修复部分问题，移除废弃函数

footer.php, inc/decorate.php, js/link-submission.js, user/page-links.php
=> 修复滤镜导致的排版问题

inc/decorate.php, js/link-submission.js
=> 降低背景滤镜层级，解决恢复滚动异常

inc/swicher.php, opt/options/theme-options.php, style.css
撤回滤镜z-index更改，因为深色模式下异常，会导致封面所有元素无法交互
https://github.com/Fuukei/Sakurairo_Scripts/pull/41
=> 更新页面设置特色图为背景，撤回一条有问题的修复

inc/chatgpt/hooks.php, inc/theme-plus.php
一处目录问题修复
修改注释解析方法，防止破坏文章内原有自定义内容（原来会直接移除所有div标签）
=> Daily Update

inc/swicher.php, js/nav.js
https://github.com/Fuukei/Sakurairo_Scripts/pull/46
修正判断逻辑，防止在列表页返回最新文章的封面
=> 修复文章封面作为背景的一些问题，修复导航岛报错的问题

inc/theme-plus.php
=> 修复：改进 macOS 版本识别逻辑，新增对最新版本的支持

style.css
=> fix: 修复项目符号错误

functions.php
Reverts mirai-mamori/Sakurairo#1225
=> Revert "仅保存需要的数据，减小传输体积"

functions.php
=> 仅保存需要的数据，减小传输体积，防止泄密

functions.php
修复访客无法使用部分富文本评论的问题
移除markdown原文保存，防止安全问题
=> 修复部分markdown评论的问题
