style.css
目前的计算样式会使toc-container在屏幕宽度接近1080px时超过body宽度导致越界
pr中新改进的样式能修复这一问题，**但是在第一次渲染时显示位置会偏左（随后会自动移动到正确的位置），造成不太好的体验**
暂且放在这等一个更好的方案
=> fix: toc container

update-checker/languages/ja_JP.po
调整27文字顺序
调整33文字顺序
调整39文法，语句修正为%s
调整44全半角，减少舶来语使用易于阅读
调整48Changelog固定词汇可保持原样
=> Update Japanese translation

inc/api.php, inc/classes/Cache.php
[自WordPress 5.5](https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/#permissions-callback
)，被要求在调用```register_rest_route()```时提供
鉴于主题目前大部分API都是公开的，暂时加上了```'__return_true'```
但是某些API或许可以趁这个机会加上鉴权限制，例如：```update_database()```或许应当只被管理员调用
大家有空看看
=> permission_callback required

functions.php
[Original Ticket](https://github.com/mirai-mamori/Sakurairo/issues/530)  #530 
- Attempting to fix Frontend Localization: Category showing in Chinese since frontend script get_locale() function mis-matched .pot file msgid.
- Before applying: [Image](https://user-images.githubusercontent.com/43423211/167981419-b8d7cec9-dd9e-4459-ad09-f7999dd6dee4.png)
- After applying: [Image](https://user-images.githubusercontent.com/43423211/167992539-9fea9484-5fc6-4a8f-bfdf-610665ab17f9.jpg)
=> fix/Issue-530: Fixed Frontend Localization: Category showing in Chinese

style.css
=> fix:行内代码填充过大导致上下行填充重叠

functions.php, inc/theme_plus.php
During our investigation, we identified that 'poi_time_since was' the source of the issue causing incorrect display of post and comment times. To address this, we modified the function to retrieve the server's time through WordPress rather than using the PHP-provided function 'time()'.
=> fix: fix 'poi_time_since' function which can make post time incorrect

functions.php
Fix: https://ivampiresp.com/2023/05/31/fix-the-issue-of-wordpress-returning-200-when-no-content
Problem: https://blog.03k.org/post/wordpress-bad.html
=> fix: 修复 WordPress 搜索结果为空，返回为 200

layouts/post-nextprev.php, page-word.php, style.css
=> 说说模板样式修正、bug修复

functions.php
无法输入的原因是loading元素全屏遮挡了输入框
理论上资源加载完成后，应该要把loading移除，但是使用transitionend事件来触发移除操作，会概率性导致无法移除loading，具体原因暂不明。从测试上来看，页面加载速度越快，该问题出现的概率越大。有一个简单的触发步骤是：登录页面加载后，不输入任何信息，连续点击“登录”按钮。另外使用缓存刷新页面也有概率能够触发。
修正的话，是弃用transitionend事件，改为延迟400ms后直接移除loading元素。之所以是400ms，是因为以前transitionend事件的动画时间就是400ms。从体验上看，没有明显的视觉变化。 
#773
=> fix: 登录页面重载时有概率导致文本框无法输入

style.css
=> fix(文章): 古腾堡编辑器创建的文章中，设定为居中对齐的图片的描述文本不居中

functions.php
1、此举会使得说说帖子能够使用区块编辑器进行编辑
2、可以通过REST API处理说说（shuoshuo）类型的帖子，以便其它应用程序使用。
备注：对应的REST API路由为：/wp-json/wp/v2/shuoshuo 或者 /?rest_route=/shuoshuo
=> 说说启用REST API支持

header.php
header.php 里面使用 is_singular() 判断当前页面，并以此来显示 description 与 keywords，但是 is_singular() 只判断当前页面是否为文章、页面、附件、自定义文章，并不包含判断当前页面是否为分类页面，而主题在 is_singular() 里面写了与分类页面 description 与 keywords展示，这是没有用处的。
这里使用 is_category() 与 category_description() 对分类页面单独进行了处理。
---
原有的 description 与 keywords 截取逻辑存在问题，例如在没有任何内容的页面中，description 或 keywords 就无法取得任何值，而直接展示为空，缺乏默认值。
改主题设置中手动填写的 keywords 与 description 为默认值，当页面 keywords 或 description 为空时。
没有写为页面时，keywords 包含该页面标题而尽可能更好的符合该页面关键词，因为这更消耗资源。
*页面时，且页面文章没有内容时，description 是否设置默认值的问题，WordPress中无法单独为页面设置介绍，直接设置一个统一的默认值有可能影响搜索引擎等展示，是否留空让爬虫自己解决？同理还有分类页面。目前这里设置了一个默认值。*
---
description 值输出时会出现带有换行的情况，keywords 循环拼接时会始终在末尾加一个英文逗号 , 
采用新的函数方法
=> Fix: 优化 head 里面 description 与 keywords 值展示逻辑。

footer.php, inc/theme_plus.php, style.css
https://github.com/mirai-mamori/Sakurairo/issues/852
入口仅在移动端请求下渲染，注册入口跟随wp设置显示
未登录情况下的效果：
用户已登录下的效果：
=> feat(menu): 移动端菜单添加用户登录、管理入口

inc/theme_plus.php
**概述:**
此更改将 current_user_can('level_10') 替换为 current_user_can('administrator')， level 数字的判断方式，官方已经建议不要再使用了，应尽量避免。
**详细描述:**
在 WordPress 中，`level_10` 是管理员用户（administrator）级别的别称。用户级别是在 [WordPress 1.5](https://codex.wordpress.org/Version_1.5) 中引入的，它们在 [WordPress 2.0](https://codex.wordpress.org/Version_2.0) 中被[角色和功能](https://codex.wordpress.org/Roles_and_Capabilities)所取代，并且在 [WordPress 3.0](https://codex.wordpress.org/Version_3.0) 中最终被弃用。
[User_Levels](https://codex.wordpress.org/User_Levels)
**其他注意事项:**
- 这个更改不会影响现有功能，仅提高了代码的健康度。
=> Update current_user_can('level_10') to current_user_can('administrator')

header.php, opt/options/theme-options.php
添加了启用pjax后跳转后仍需反复重新加载的脚本的内容，
少部分玩家可能在footer处引入了动态添加备案信息的玩法或者自定义增删全局内容的玩法，
但是很遗憾，为了能启用不中断播放的页底播放器，在启用pjax后这些脚本会在跳转后失效，
在header处引用虽然能加载但是动态修改内容功能无效了，所以现在需要在pjax加载完成后刷新一遍。
这段代码可以让那些魔改玩法保活。
=>  修复启用pjax后footer处自定义增删内容脚本不再重新加载的bug

search.php
通过检索发现 content-thumb 模板涉及到主页和作者页的文章排序展示，不方便进行搜索方法编写，该改进仅针对搜索功能，
所以直接在搜索页模板进行修改。
通过先分类搜索符合关键词的内容，然后将分类的内容合并实现了置顶的相关结果优先展示
经过本地和线上测试有效，使用了官方的测试内容和十几篇随机文章和说说测试了部分关键词的搜索
=> 尝试修复了站内搜索的功能

opt/classes/admin-options.class.php
全新安装的wordpress，安装并启用主题，在未进主题设置页面保存设置的情况下，打开网站首页。
在首次安装启动时，点击应用主题按钮后，主题会初始化，理论上会将有默认设置的选项写进数据库中，实际上也本应如此。
但是有几行代码，没有遵循主题的初始化步骤，直接把选项的值写进数据库中，导致了主题默认选项无法进行初始化。表象是打开首页白屏，如上图片所示。
https://github.com/mirai-mamori/Sakurairo/blob/93046f03196dea23a1d45dd2a85aca3749088518/opt/classes/admin-options.class.php#L197-L199
上面的代码是主题初始化过程中，写入选项默认值的逻辑：判断从数据库中获取到的设置项是否为空，如果为空，说明是一个船新安装的wordpress，然后写入默认值。
这很合理，但是有几个函数影响了这一个判断：
https://github.com/mirai-mamori/Sakurairo/blob/93046f03196dea23a1d45dd2a85aca3749088518/functions.php#L720-L797
functions.php里的函数会先于主题设置项初始化执行，导致的结果是，在主题设置项初始化之前，数据库中已经存在了数条设置项的默认值，进而当主题设置项初始化时，`$tmp_options`的值不为空，无法将默认值写入数据库中。
无论如何刷新首页，都是白屏，只能通过在后台设置中保存主题设置项解决这个问题。
很简单，将判断条件更改为数据库设置项的key与选项定义里的key是否完全相符就可以了，如果不相符，说明未完全初始化。
=> fix(csf): 首次安装启用主题时首页白屏

header.php
改用使用javascript加载保活脚本，之前在页脚插入的方式太蠢了（之前到底是哪个天才想出来这么个馊主意？没错，是我）
=> 更换保活脚本的方式，发现直接插入页面不加载了

inc/decorate.php
Fix the issue where the article summary is truncated in certain cases.
Before:
After:
~~***Update JS bundle to https://github.com/Fuukei/Sakurairo_Scripts/commit/111ad634d4c9778db6fab72c38cb5427b366a4a0 and fixed https://github.com/mirai-mamori/Sakurairo/issues/997***~~ (Removed after discussion.)
=> Daily Update (?

header.php
使用 WordPress 编辑器的脚注功能时，点击脚注会打开新的标签页。对 `<a>` 标签包裹的以 `#` 开头的跳转链接将全部进行页面内的跳转
=> WordPress 脚注仅在本页内跳转

functions.php
自定义表情功能添加输出详细实际读取路径
方便不同用户在不同的环境下可能存在差异的情况下自行排除错误
=> 自定义表情设置添加详细的路径信息输出

style.css
限制目录的最大高度让滚动条能够正常工作
让撑出视野部分的目录标题能够以滚动的方式允许用户预览并选择跳转
修改了部分目录的鼠标样式，现在只有在文字上时，鼠标样式才会变成pointer，更符合用户直觉
前：
后：
=> 限制目录的高度，确保内容不会超出窗口，修改了部分区域的鼠标样式

opt/options/theme-options.php
搜索页内容筛选不需要依赖于过滤器开启
过滤器仅作为自定义访客体验的可选项
=> 搜索页内容筛选不再依托于过滤器是否开启

style.css
修复前
修复后：
缩小了引号的大小，不再显得夸张，也不会在评论区被渲染时遮挡部分信息
=> 更改blockquote的样式，确保手机端引用正常显示

style.css
重置404页面动图的动画属性
原来动画无法正常播放，仅在页面切换、滑动时缓慢、卡顿刷新
把它的动画样式去掉就好了
修改了展示区第二种形式的动画，不再突然出现而显得突兀，并添加了些微文字描边，以适应各种颜色的图片。
=> 修复了部分动画，修改了部分样式

inc/api.php, inc/classes/bangumi.php, opt/options/theme-options.php, user/page-bangumi.php
效果：https://nicocat.cc/animelist/
使用[Bangumi API](https://bangumi.github.io/api/)，显示看过和正在看的番剧
=> 追番页添加bangumi支持

functions.php, opt/options/theme-options.php
填写`仓库链接`或者`用户名/仓库`都能识别  
[ghcard path="mirai-mamori/Sakurairo"][/ghcard]  
[ghcard path="https://github.com/mirai-mamori/Sakurairo"][/ghcard]
旧的也兼容  
[ghcard path="mirai-mamori/Sakurairo"]/pin/?username=mirai-mamori&repo=Sakurairo[/ghcard]
添加了为用户代理vercel.app获取卡片的选项
=> 更方便的github仓库卡片短代码

inc/classes/Captcha.php, inc/swicher.php, opt/options/theme-options.php
将原来的图形验证码替换成计算题，
验证码的复杂和清晰度会随难度而动态变化，
可在主题配置里自行调整，以下为Demo：
- 难度为0
- 难度70 (默认)
- 难度100
- 同时使用0~100的滑块作为难度配置
=> 替换主题验证码为计算题，加入难度配置

js/nav.js, style.css
现在子菜单默认禁止交互
通过主菜单选项激活后才可以交互
有且仅有一个子菜单可以交互
防止部分用户鼠标移动太快出现两个子菜单冲突的量子叠加态
更新前：
https://github.com/user-attachments/assets/24b29f8b-e78b-41af-ba97-34a900ced659
更新后：
https://github.com/user-attachments/assets/25ff4da7-7cf4-4a36-ad41-915f4cebd854
=> 更新菜单交互逻辑，防止出现量子叠加态

inc/classes/MyAnimeList.php
=> 修复mal模版一处编码问题导致的报错

inc/theme_plus.php, layouts/imgbox.php, tpl/content-thumbcard.php, tpl/entry-census.php, tpl/single-entry-header.php, update-checker/Puc/v5p1/Theme/Package.php
原先所使用的`get_stylesheet_directory`接口总是获取当前主题的根目录，这会导致子主题创建错误。
当用户从sakurairo创建子主题时，代码会试图从子主题寻找该文件，这会导致找不到文件从而报错。
例如文件`layouts\imgbox.php`中有如下代码
```php
<?php
include(get_stylesheet_directory().'/layouts/all_opt.php');
...
```
它总是会去找当前主题下的`'/layouts/all_opt.php'`文件。而用户一旦从sakurairo主题创建子主题，它就会尝试寻找子主题下的`'/layouts/all_opt.php'`文件——这个文件不存在于是就报错了。
而期望的行为应该是从父亲主题寻找该文件。
所以，这些地方应该使用`get_template_directory`接口。
这两个接口的区别如下：
- `get_stylesheet_directory`，总是返回当前主题的绝对路径，无论是否为子主题。
- `get_template_directory`，如果当前启用的主题是一个子主题，该函数返回父主题的主题目录的服务器绝对路径；否则，返回当前主题的绝对路径。
于是换用该接口后，这些地方总是返回父主题（也即sakurairo主题）的绝对路径。
修复该bug后，可以正常从sakurairo主题创建子主题。
=> Fix bug: child-theme failure 修复子主题创建问题

opt/options/theme-options.php
设置项说明中一处多余的空格，导致跳转[](https://prismjs.com/%20plugins/file-highlight/)，404页
=> 删除设置项说明中一处多余的空格

inc/classes/Captcha.php, inc/classes/Images.php
在这个PR (https://github.com/mirai-mamori/Sakurairo/pull/1036) 中，修复了使用错误接口导致的子主题创建错误问题。
现在发现，仍有一些未修正的错误。此前发现的错误使用的都是`get_stylesheet_directory()`；而本次发现的则是更旧的接口`STYLESHEETPATH`. 两个接口的行为是一致的，都会导致子主题创建错误。
当用户从sakurairo创建子主题时，代码会试图从子主题寻找该文件，这会导致找不到文件从而报错。
例如如下代码就是不推荐的：
```php
include(get_stylesheet_directory().'/layouts/all_opt.php');
```
它总是会去找当前主题下的`'/layouts/all_opt.php'`文件。而用户一旦从sakurairo主题创建子主题，它就会尝试寻找子主题下的`'/layouts/all_opt.php'`文件——这个文件不存在于是就报错了。
例如，现在验证码功能中如下代码就是不推荐的：
```php
$font = STYLESHEETPATH . '/inc/KumoFont.ttf';
```
它也总是会去找当前主题下的`'/inc/KumoFont.ttf'`文件，因为相同的原因导致报错。
而期望的行为应该是从父亲主题寻找该文件。
所以，这些地方应该使用`get_template_directory`接口。
这两个接口的区别如下：
- `get_stylesheet_directory`，总是返回当前主题的绝对路径，无论是否为子主题。
- `get_template_directory`，如果当前启用的主题是一个子主题，该函数返回父主题的主题目录的服务器绝对路径；否则，返回当前主题的绝对路径。 …
=> Fix bug: child-theme failure caused by deprecated API 修复弃用API引起的子主题创建问题

functions.php, inc/theme_plus.php, search.php
current_user_can() 用于检查权限而非角色。直接使用 'administrator'（角色名）检查会不可靠。
管理员角色的核心权限是 manage_options，其他插件可能修改角色权限关系。
=> 修复不恰当的权限判断

css/sakura_header.css, header.php, inc/decorate.php, js/nav.js, layouts/sakura_header.php, opt/options/theme-options.php, style.css
https://github.com/user-attachments/assets/fd7090d9-4afc-4309-8794-84100b0aaffe
使用层叠样式的方法部分复刻了Sakura和Sakurairo经典样式导航栏，
使用Sakura样式时nav.js仅加载防止二级菜单叠加的部分，
设置项面板的部分图片现在也可以使用自定义的前端资源路径
=> 复刻sakura导航栏样式，修改设置项图片采用自定义前端资源路径，新样式和Sakura样式子菜单均可以居中对齐

style.css
=> 修复在top-social的v1中，鼠标在Inner上鬼畜的问题，并去除了深色模式下多余的边角

inc/theme_plus.php
原内建图床已移除，改为使用functions中的文章卡片封面随机图获取方法
=> 上下篇预览随机图和文章封面统一

functions.php
```php
// default feature image
function DEFAULT_FEATURE_IMAGE()
{
//使用独立外部api
if (iro_opt('post_cover_options') == 'type_2') {
$url = iro_opt('post_cover');
return $url ? get_random_url($url) : '';
}
//使用内建
if (iro_opt('random_graphs_options') == 'gallery') {
$url = rest_url('sakura/v1/gallery') . '?img=w';
return get_random_url($url);
}
//使用封面外部
if (iro_opt('random_graphs_options') == 'external_api') {
$url = iro_opt('random_graphs_link');
return $url ? get_random_url($url) : '';
}
//意外情况
$url = iro_opt('random_graphs_link');
return $url ? get_random_url($url) : '';
}
```
=> 修复了DEFAULT_FEATURE_IMAGE()返回null值导致Fatal Error的问题

js/nav.js
从主页进入文章页面，滚动显示标题，刷新后后退至主页，导航栏长度异常。
刷新后`StateManager`保留非主页状态，浏览器后退未正确重置，导致宽度计算错误。
添加`popstate`事件监听器，在后退至主页时重置状态并重新初始化。
- `popstate`在浏览器导航时触发。
- 清除并重新初始化`StateManager`以确保在返回主页时获得新状态。
- 调用`showBgNext`以正确显示`bgNext`。
在主页加载未完成时进入文章页面，导航栏长度异常。
如果主页未完全加载，`StateManager`和宽度未初始化，过渡到文章页面跳过了适当的宽度设置，导致`navSearchWrapper`保留未调整的宽度。
确保`InitController`在页面过渡前完成初始化。
- 将初始化移到顶部，确保在任何逻辑之前运行。
- 使用`state`中存储的`measuredWidths`保持一致性。
- 通过依赖`InitController`的稳健测量简化逻辑，防止未初始化的过渡。
=> 修复了新版导航栏的一些问题

opt/options/theme-options.php
`wechat_copy_switch`与`qq_copy_switch`应为默认开启。
=> 纠正wechat_copy_switch与qq_copy_switch的默认值

style.css
- 优化了页码的省略号显示
- 恢复了列表项的项目编号，同时优化了使用 `<ul>` `<ol>` 构建的组件无项目编号冲突
=> fix: 修复页码样式遗漏，优化<ul><ol>的list项目编号

functions.php
之前的整理方法会将文章密码、原文结构等敏感信息包含在归档信息中，现在不会了
=> 仅保存需要的数据，减小传输体积

css/content-style/sakura.css
wordpress编辑器自带三种分割线样式，包含主题已有的点状分割线
=> 正文分割线样式使用wordpress编辑器样式的不使用主题样式
